/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import graphics.GeocoderExample;
import tools.JSonParser;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.Point;
import java.io.IOException;
import java.util.Vector;

import org.json.simple.parser.ParseException;

/**
 *
 * @author Pavan
 */
public class Frm_Main extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Main
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cbo_cuisine;
    private javax.swing.JComboBox<String> cbo_sortby;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_cuisine;
    private javax.swing.JLabel lbl_cuisine1;
    private javax.swing.JLabel lbl_header;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_sortby;
    private javax.swing.JList<String> lst_restaurants;
    public javax.swing.JPanel pnl_header;
    private static javax.swing.JPanel pnl_map;
    private javax.swing.JPanel pnl_results;
    private javax.swing.JPanel pnl_search;
    private javax.swing.JTextField txt_searchrange;
    // End of variables declaration//GEN-END:variables
    
    
    public static Vector<String> restuarantName =  new Vector<String>();
	
    public Frm_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header = new javax.swing.JPanel();
        lbl_header = new javax.swing.JLabel();
        pnl_search = new javax.swing.JPanel();
        lbl_search = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_cuisine = new javax.swing.JLabel();
        lbl_cuisine1 = new javax.swing.JLabel();
        txt_searchrange = new javax.swing.JTextField();
        cbo_cuisine = new javax.swing.JComboBox<>();
        btn_search = new javax.swing.JButton();
        pnl_results = new javax.swing.JPanel();
        lbl_result = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_restaurants = new javax.swing.JList<>();
        lbl_sortby = new javax.swing.JLabel();
        cbo_sortby = new javax.swing.JComboBox<>();
        pnl_map = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 50));
        setName("Main Page"); // NOI18N
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        pnl_header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_header.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lbl_header.setForeground(new java.awt.Color(0, 102, 204));
        lbl_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_header.setText("              Top Dominating Restaurants Finder");

        javax.swing.GroupLayout pnl_headerLayout = new javax.swing.GroupLayout(pnl_header);
        pnl_header.setLayout(pnl_headerLayout);
        pnl_headerLayout.setHorizontalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_header, javax.swing.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_headerLayout.setVerticalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_headerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_header)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pnl_search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_search.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lbl_search.setText("Search");

        lbl_cuisine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cuisine.setText("Cuisine:");

        lbl_cuisine1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cuisine1.setText("Searching Range/Distance (mile):");

        txt_searchrange.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_searchrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchrangeActionPerformed(evt);
            }
        });

        cbo_cuisine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_cuisine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a cuisine ...", "American", "Italian", "Mexican", "Chinese", "Indian", "Nepalese" }));

        btn_search.setBackground(new java.awt.Color(0, 102, 204));
        btn_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setText("Search");

        javax.swing.GroupLayout pnl_searchLayout = new javax.swing.GroupLayout(pnl_search);
        pnl_search.setLayout(pnl_searchLayout);
        pnl_searchLayout.setHorizontalGroup(
            pnl_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnl_searchLayout.createSequentialGroup()
                .addGroup(pnl_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_searchLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lbl_search))
                    .addGroup(pnl_searchLayout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addGroup(pnl_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_searchLayout.createSequentialGroup()
                                .addComponent(lbl_cuisine)
                                .addGap(18, 18, 18)
                                .addComponent(cbo_cuisine, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_searchLayout.createSequentialGroup()
                                .addComponent(lbl_cuisine1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_searchrange, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(pnl_searchLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btn_search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_searchLayout.setVerticalGroup(
            pnl_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_searchLayout.createSequentialGroup()
                .addComponent(lbl_search, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cuisine)
                    .addComponent(cbo_cuisine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cuisine1)
                    .addComponent(txt_searchrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_search)
                .addGap(21, 21, 21))
        );

        pnl_results.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_result.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lbl_result.setText("Results");

        lst_restaurants.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        
        Vector<String> vec  = restuarantName;
        
        System.out.println(vec.size());
        
        lst_restaurants.setModel(new javax.swing.AbstractListModel<String>() 
        {
            String[] strings = { "1. Restaurant 1", "2. Restaurant 2", "3. Restaurant 3", "4. Restaurant 4", "5. Restaurant 5" };
            
            public int getSize() { 
            	
            	if (vec.size() == 0)
            	
            	return strings.length; 
            	
            	else 
            		return vec.size();
            }
            
            public String getElementAt(int i)
            { 
            	if (vec.size() == 0)
            	return strings[i]; 
            	
            	else return vec.get(i).toString();
            	
            }
        });
        jScrollPane1.setViewportView(lst_restaurants);

        lbl_sortby.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_sortby.setText("Sort by");

        cbo_sortby.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbo_sortby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Top Dominating Score", "Dominating Price", "Dominating Distance", "Dominating Ratings" }));

        javax.swing.GroupLayout pnl_resultsLayout = new javax.swing.GroupLayout(pnl_results);
        pnl_results.setLayout(pnl_resultsLayout);
        pnl_resultsLayout.setHorizontalGroup(
            pnl_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(pnl_resultsLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lbl_result)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_resultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnl_resultsLayout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addComponent(lbl_sortby)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbo_sortby, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_resultsLayout.setVerticalGroup(
            pnl_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_resultsLayout.createSequentialGroup()
                .addComponent(lbl_result, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_sortby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sortby))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
        );

        pnl_map.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_map.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnl_results, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_map, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnl_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_results, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnl_map, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchrangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchrangeActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
       if ((evt.getNewState() & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH){
//           Point newLocation = this.getContentPane().getLocationOnScreen();
//           newLocation.translate(400, 15);
//           lbl_header.setBounds(500, 10, lbl_header.getWidth(), lbl_header.getHeight());
//           //this.pnl_header.removeAll();
//           this.pnl_header.add(lbl_header);
//           this.pnl_header.validate();
       }
    }//GEN-LAST:event_formWindowStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                GeocoderExample mapView = new GeocoderExample();
       
                
                try {
					String str = JSonParser.RestaurantsWithInRadius(41.1536674 , -81.3578859 , "Mexican" , JSonParser.KEy , 4);
					JSonParser.getData(str);		
					
					restuarantName  = JSonParser.getResVec();
			         Frm_Main mainFrame = new Frm_Main();
		             mainFrame.pnl_map.removeAll();
					Vector<String > strPid  = JSonParser.getResPID();
		                
		                for (int i = 0 ; i < restuarantName.size() ; i++ )
		                {
		                	System.out.println(restuarantName.get(i).toString());
		                    mapView.performGeocode( restuarantName.get(i).toString() );
		                }
		            
		                
		                mainFrame.pnl_map.add(mapView, BorderLayout.CENTER);
		                mainFrame.pnl_map.validate();
		                mainFrame.pnl_map.setVisible(true);
		                //mainFrame.add(pnl_map);
		                mainFrame.setVisible(true);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
             
            }
        });
    }

}
